// <auto-generated />
using System;
using MVC_Projec2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_Projec2.Migrations
{
    [DbContext(typeof(MVCProjectContext))]
    partial class MVCProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC_Projec2.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("MVC_Projec2.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "09970960-568f-421a-855d-9c2e22205af2",
                            AccessFailedCount = 0,

                         


                            ConcurrencyStamp = "b65df7bb-22a7-458d-a45c-1b3e9b1839d6",

                          CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJjlvyUgIDaLHTZqCpMD4gHnkv9e887fOkJiDjF2xGoJwtY5efw4JiNI6SRUpKbmyQ==",
                            PhoneNumber = "0123456789",
                            PhoneNumberConfirmed = true,




                            SecurityStamp = "8a1ac1fa-3358-4d40-b9e7-a890c9aac316",

                            TwoFactorEnabled = false,
                            UserName = "admin@example.com"
                        },
                        new
                        {
                            Id = "8aa98e10-33a4-412a-8cd4-edb609f077d5",
                            AccessFailedCount = 0,




                            ConcurrencyStamp = "0a03c815-7c19-4e35-9da9-b5b3eb47c04a",

                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@EXAMPLE.COM",
                            NormalizedUserName = "USER@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIP/W0E/SkD5mRD9O4dSxOz6kjNG8YMgiCr7zdTs/ZGegstn0eDd/puIbkqQNC6+bg==",
                            PhoneNumber = "9876543210",
                            PhoneNumberConfirmed = true,




                            SecurityStamp = "fe9b6409-a3f8-4a53-ae69-0f77d155b1d1",

                            TwoFactorEnabled = false,
                            UserName = "user@example.com"
                        });
                });

            modelBuilder.Entity("MVC_Projec2.Models.Atelier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("priceRange")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Ateliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "atelier2.jpg",
                            Location = "Uptown",
                            Name = "Elite Atelier",
                            priceRange = 9000.0
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "atelier1.jpg",
                            Location = "Downtown",
                            Name = "Royal Designs",
                            priceRange = 5000.0
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "atelier5.jpg",
                            Location = "Easttown",
                            Name = "Glamorous Styles",
                            priceRange = 4000.0
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "atelier3.jpg",
                            Location = "Westtown",
                            Name = "Elegant Creations",
                            priceRange = 12000.0
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "atelier4.jpg",
                            Location = "Downtown",
                            Name = "Chic Styles",
                            priceRange = 6000.0
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "atelier7.jpg",
                            Location = "Uptown",
                            Name = "Vintage Touch",
                            priceRange = 8000.0
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "atelier5.jpg",
                            Location = "Downtown",
                            Name = "Modern Artistry",
                            priceRange = 2000.0
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "atelier1.jpg",
                            Location = "East End",
                            Name = "Exquisite Design",
                            priceRange = 3000.0
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "Atelier (3).jpeg",
                            Location = "West End",
                            Name = "Timeless Beauty",
                            priceRange = 8000.0
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "Atelier (19).jpeg",
                            Location = "Central Square",
                            Name = "Fashion Forward",
                            priceRange = 7000.0
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "Atelier (20).jpeg",
                            Location = "Central Square",
                            Name = "Style Studio",
                            priceRange = 1500.0
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "Atelier (21).jpeg",
                            Location = "Central Square",
                            Name = "Elegance Edge",
                            priceRange = 5500.0
                        },
                        new
                        {
                            Id = 13,
                            ImageUrl = "Atelier (22).jpeg",
                            Location = "Central Square",
                            Name = "Vogue Venue",
                            priceRange = 2400.0
                        },
                        new
                        {
                            Id = 14,
                            ImageUrl = "Atelier (23).jpeg",
                            Location = "Central Square",
                            Name = "Chic Charm",
                            priceRange = 8200.0
                        },
                        new
                        {
                            Id = 15,
                            ImageUrl = "Atelier (24).jpeg",
                            Location = "Central Square",
                            Name = "Glamour Gate",
                            priceRange = 4300.0
                        },
                        new
                        {
                            Id = 16,
                            ImageUrl = "Atelier (25).jpeg",
                            Location = "Central Square",
                            Name = "Runway Room",
                            priceRange = 4200.0
                        },
                        new
                        {
                            Id = 17,
                            ImageUrl = "Atelier (26).jpeg",
                            Location = "Central Square",
                            Name = "Trendy Touch",
                            priceRange = 3500.0
                        },
                        new
                        {
                            Id = 18,
                            ImageUrl = "Atelier (27).jpeg",
                            Location = "Central Square",
                            Name = "Haute Hub",
                            priceRange = 2900.0
                        },
                        new
                        {
                            Id = 19,
                            ImageUrl = "Atelier (28).jpeg",
                            Location = "Central Square",
                            Name = "Modish Moments",
                            priceRange = 4400.0
                        },
                        new
                        {
                            Id = 20,
                            ImageUrl = "Atelier (29).jpeg",
                            Location = "Central Square",
                            Name = "Catwalk Corner",
                            priceRange = 1100.0
                        });
                });

            modelBuilder.Entity("MVC_Projec2.Models.AtelierImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtelierId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AtelierId");

                    b.ToTable("AtelierImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AtelierId = 1,
                            ImageUrl = "atelier1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            AtelierId = 1,
                            ImageUrl = "atelier2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            AtelierId = 1,
                            ImageUrl = "atelier3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            AtelierId = 2,
                            ImageUrl = "atelier4.jpg"
                        },
                        new
                        {
                            Id = 5,
                            AtelierId = 2,
                            ImageUrl = "atelier5.jpg"
                        },
                        new
                        {
                            Id = 6,
                            AtelierId = 2,
                            ImageUrl = "atelier6.jpg"
                        },
                        new
                        {
                            Id = 7,
                            AtelierId = 3,
                            ImageUrl = "atelier7.jpg"
                        },
                        new
                        {
                            Id = 8,
                            AtelierId = 3,
                            ImageUrl = "Atelier (1).jpeg"
                        },
                        new
                        {
                            Id = 9,
                            AtelierId = 3,
                            ImageUrl = "Atelier (2).jpeg"
                        },
                        new
                        {
                            Id = 10,
                            AtelierId = 4,
                            ImageUrl = "Atelier (3).jpeg"
                        },
                        new
                        {
                            Id = 11,
                            AtelierId = 4,
                            ImageUrl = "atelier1.jpg"
                        },
                        new
                        {
                            Id = 12,
                            AtelierId = 4,
                            ImageUrl = "Atelier (20).jpeg"
                        },
                        new
                        {
                            Id = 13,
                            AtelierId = 5,
                            ImageUrl = "Atelier (21).jpeg"
                        },
                        new
                        {
                            Id = 14,
                            AtelierId = 5,
                            ImageUrl = "Atelier (22).jpeg"
                        },
                        new
                        {
                            Id = 15,
                            AtelierId = 5,
                            ImageUrl = "Atelier (23).jpeg"
                        },
                        new
                        {
                            Id = 16,
                            AtelierId = 6,
                            ImageUrl = "Atelier (24).jpeg"
                        },
                        new
                        {
                            Id = 17,
                            AtelierId = 6,
                            ImageUrl = "Atelier (25).jpeg"
                        },
                        new
                        {
                            Id = 18,
                            AtelierId = 6,
                            ImageUrl = "Atelier (26).jpeg"
                        },
                        new
                        {
                            Id = 19,
                            AtelierId = 7,
                            ImageUrl = "Atelier (27).jpeg"
                        },
                        new
                        {
                            Id = 20,
                            AtelierId = 7,
                            ImageUrl = "Atelier (28).jpeg"
                        },
                        new
                        {
                            Id = 21,
                            AtelierId = 7,
                            ImageUrl = "Atelier (29).jpeg"
                        },
                        new
                        {
                            Id = 22,
                            AtelierId = 7,
                            ImageUrl = "Atelier (4).jpeg"
                        },
                        new
                        {
                            Id = 23,
                            AtelierId = 8,
                            ImageUrl = "Atelier (5).jpeg"
                        },
                        new
                        {
                            Id = 24,
                            AtelierId = 8,
                            ImageUrl = "Atelier (6).jpeg"
                        },
                        new
                        {
                            Id = 25,
                            AtelierId = 8,
                            ImageUrl = "Atelier (7).jpeg"
                        },
                        new
                        {
                            Id = 26,
                            AtelierId = 9,
                            ImageUrl = "Atelier (8).jpeg"
                        },
                        new
                        {
                            Id = 27,
                            AtelierId = 9,
                            ImageUrl = "Atelier (9).jpeg"
                        },
                        new
                        {
                            Id = 28,
                            AtelierId = 9,
                            ImageUrl = "Atelier (10).jpeg"
                        },
                        new
                        {
                            Id = 29,
                            AtelierId = 10,
                            ImageUrl = "Atelier (11).jpeg"
                        },
                        new
                        {
                            Id = 30,
                            AtelierId = 10,
                            ImageUrl = "Atelier (12).jpeg"
                        },
                        new
                        {
                            Id = 31,
                            AtelierId = 10,
                            ImageUrl = "Atelier (13).jpeg"
                        },
                        new
                        {
                            Id = 32,
                            AtelierId = 11,
                            ImageUrl = "Atelier (14).jpeg"
                        },
                        new
                        {
                            Id = 33,
                            AtelierId = 11,
                            ImageUrl = "Atelier (15).jpeg"
                        },
                        new
                        {
                            Id = 34,
                            AtelierId = 11,
                            ImageUrl = "Atelier (16).jpeg"
                        },
                        new
                        {
                            Id = 35,
                            AtelierId = 12,
                            ImageUrl = "Atelier (17).jpeg"
                        },
                        new
                        {
                            Id = 36,
                            AtelierId = 12,
                            ImageUrl = "Atelier (18).jpeg"
                        },
                        new
                        {
                            Id = 37,
                            AtelierId = 12,
                            ImageUrl = "Atelier (19).jpeg"
                        },
                        new
                        {
                            Id = 38,
                            AtelierId = 13,
                            ImageUrl = "Atelier (1).jpeg"
                        },
                        new
                        {
                            Id = 39,
                            AtelierId = 13,
                            ImageUrl = "Atelier (5).jpeg"
                        },
                        new
                        {
                            Id = 40,
                            AtelierId = 13,
                            ImageUrl = "Atelier (9).jpeg"
                        },
                        new
                        {
                            Id = 41,
                            AtelierId = 14,
                            ImageUrl = "Atelier (20).jpeg"
                        },
                        new
                        {
                            Id = 42,
                            AtelierId = 14,
                            ImageUrl = "Atelier (15).jpeg"
                        });
                });

            modelBuilder.Entity("MVC_Projec2.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Atelier_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Decor_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Hall_Id")
                        .HasColumnType("int");

                    b.Property<int?>("MakeupId")
                        .HasColumnType("int");

                    b.Property<int?>("Session_Id")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Atelier_Id");

                    b.HasIndex("Decor_Id");

                    b.HasIndex("Hall_Id");

                    b.HasIndex("MakeupId");

                    b.HasIndex("Session_Id");

                    b.HasIndex("user_id");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Atelier_Id = 3,




                            Created_at = new DateTime(2025, 4, 13, 12, 8, 19, 558, DateTimeKind.Local).AddTicks(8980),

                            Decor_Id = 1,
                            Hall_Id = 2,
                            MakeupId = 1,
                            Session_Id = 2,
                            Status = "Confirmed",




                            user_id = "09970960-568f-421a-855d-9c2e22205af2"

                        },
                        new
                        {
                            Id = 2,
                            Atelier_Id = 1,
                            Created_at = new DateTime(2025, 4, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Decor_Id = 2,
                            Hall_Id = 1,
                            MakeupId = 4,
                            Session_Id = 1,
                            Status = "Pending",




                            user_id = "09970960-568f-421a-855d-9c2e22205af2"

                        },
                        new
                        {
                            Id = 3,
                            Atelier_Id = 3,




                            Created_at = new DateTime(2025, 4, 13, 12, 8, 19, 558, DateTimeKind.Local).AddTicks(9117),

                            Decor_Id = 1,
                            Hall_Id = 2,
                            MakeupId = 1,
                            Session_Id = 2,
                            Status = "Confirmed",



                            user_id = "09970960-568f-421a-855d-9c2e22205af2"

                        },
                        new
                        {
                            Id = 4,
                            Atelier_Id = 1,
                            Created_at = new DateTime(2025, 4, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Decor_Id = 2,
                            Hall_Id = 1,
                            MakeupId = 4,
                            Session_Id = 1,
                            Status = "Pending",




                            user_id = "09970960-568f-421a-855d-9c2e22205af2"

                        });
                });

            modelBuilder.Entity("MVC_Projec2.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceType")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Excellent service!",


                            

                         


                            CreatedAt = new DateTime(2025, 4, 13, 12, 8, 19, 558, DateTimeKind.Local).AddTicks(9188),
                            ServiceId = 0,
                            ServiceType = 0,
                            UserId = "09970960-568f-421a-855d-9c2e22205af2"

                        });
                });

            modelBuilder.Entity("MVC_Projec2.Models.Decor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Decors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Timeless elegance with ornate details and rich colors.",
                            ImageUrl = "decor1.jpg",
                            Price = 5000,
                            Style = "Classic"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sleek lines and neutral tones for a chic, modern vibe.",
                            ImageUrl = "decor2.jpg",
                            Price = 7000,
                            Style = "Modern"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Warm and cozy decor with natural wood and earthy tones.",
                            ImageUrl = "decor3.jpg",
                            Price = 4500,
                            Style = "Rustic"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Retro charm with antique pieces and soft pastels.",
                            ImageUrl = "decor4.jpg",
                            Price = 5500,
                            Style = "Vintage"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Urban-inspired look with metal accents and raw finishes.",
                            ImageUrl = "decor5.jpg",
                            Price = 6000,
                            Style = "Industrial"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Free-spirited design with bold colors and eclectic elements.",
                            ImageUrl = "decor1.jpg",
                            Price = 4000,
                            Style = "Boho"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Clean lines, simplicity, and clutter-free design.",
                            ImageUrl = "decor3.jpg",
                            Price = 6500,
                            Style = "Minimalist"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Glamorous style with bold geometry and luxurious finishes.",
                            ImageUrl = "decor6.jpg",
                            Price = 7000,
                            Style = "Art Deco"
                        },
                        new
                        {
                            Id = 9,
                            Description = "High-end sparkle with crystal accents and rich fabrics.",
                            ImageUrl = "decor5.jpg",
                            Price = 8000,
                            Style = "Glam"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Soft, feminine style with distressed furniture and florals.",
                            ImageUrl = "decor2.jpg",
                            Price = 4500,
                            Style = "Shabby Chic"
                        });
                });

            modelBuilder.Entity("MVC_Projec2.Models.DecoreImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DecorId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DecorId");

                    b.ToTable("DecoreImage");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DecorId = 1,
                            ImageUrl = "decor1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            DecorId = 1,
                            ImageUrl = "decor2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            DecorId = 1,
                            ImageUrl = "decor3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            DecorId = 2,
                            ImageUrl = "decor4.jpg"
                        },
                        new
                        {
                            Id = 5,
                            DecorId = 2,
                            ImageUrl = "decor5.jpg"
                        },
                        new
                        {
                            Id = 6,
                            DecorId = 2,
                            ImageUrl = "decor6.jpg"
                        },
                        new
                        {
                            Id = 7,
                            DecorId = 3,
                            ImageUrl = "decor2.jpg"
                        },
                        new
                        {
                            Id = 8,
                            DecorId = 3,
                            ImageUrl = "decor3.jpg"
                        },
                        new
                        {
                            Id = 9,
                            DecorId = 3,
                            ImageUrl = "decor4.jpg"
                        },
                        new
                        {
                            Id = 10,
                            DecorId = 4,
                            ImageUrl = "decor1.jpg"
                        },
                        new
                        {
                            Id = 11,
                            DecorId = 4,
                            ImageUrl = "decor2.jpg"
                        },
                        new
                        {
                            Id = 12,
                            DecorId = 4,
                            ImageUrl = "decor5.jpg"
                        },
                        new
                        {
                            Id = 13,
                            DecorId = 5,
                            ImageUrl = "decor2.jpg"
                        },
                        new
                        {
                            Id = 14,
                            DecorId = 5,
                            ImageUrl = "decor3.jpg"
                        },
                        new
                        {
                            Id = 15,
                            DecorId = 5,
                            ImageUrl = "decor4.jpg"
                        });
                });

            modelBuilder.Entity("MVC_Projec2.Models.Hall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Halls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 500,
                            ImageUrl = "hall1.jpg",
                            Location = "Downtown",
                            Name = "Grand Hall",
                            Price = 10000.0
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 300,
                            ImageUrl = "hall2.jpg",
                            Location = "City Center",
                            Name = "Crystal Ballroom",
                            Price = 7500.0
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 200,
                            ImageUrl = "hall3.jpg",
                            Location = "Beachside",
                            Name = "Sunset Venue",
                            Price = 6000.0
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 400,
                            ImageUrl = "hall4.jpg",
                            Location = "Uptown",
                            Name = "Majestic Hall",
                            Price = 9000.0
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 350,
                            ImageUrl = "Hall (5).jpeg",
                            Location = "Coastal Road",
                            Name = "Ocean View",
                            Price = 8500.0
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 600,
                            ImageUrl = "hall1.jpg",
                            Location = "High Tower",
                            Name = "Skyline Pavilion",
                            Price = 12000.0
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 250,
                            ImageUrl = "hall2.jpg",
                            Location = "Garden District",
                            Name = "Moonlight Hall",
                            Price = 7000.0
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 450,
                            ImageUrl = "hall3.jpg",
                            Location = "Palace Street",
                            Name = "Royal Suite",
                            Price = 11000.0
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 500,
                            ImageUrl = "hall4.jpg",
                            Location = "Central Park",
                            Name = "Elite Venue",
                            Price = 10500.0
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 700,
                            ImageUrl = "hall3.jpg",
                            Location = "Mountain View",
                            Name = "Luxury Retreat",
                            Price = 13000.0
                        });
                });

            modelBuilder.Entity("MVC_Projec2.Models.HallImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HallId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HallId");

                    b.ToTable("HallImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HallId = 1,
                            ImageUrl = "hall1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            HallId = 1,
                            ImageUrl = "hall2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            HallId = 1,
                            ImageUrl = "hall3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            HallId = 2,
                            ImageUrl = "hall4.jpg"
                        },
                        new
                        {
                            Id = 5,
                            HallId = 2,
                            ImageUrl = "Hall (5).jpeg"
                        },
                        new
                        {
                            Id = 6,
                            HallId = 2,
                            ImageUrl = "Hall (6).jpeg"
                        },
                        new
                        {
                            Id = 7,
                            HallId = 3,
                            ImageUrl = "Hall (7).jpeg"
                        },
                        new
                        {
                            Id = 8,
                            HallId = 3,
                            ImageUrl = "Hall (8).jpeg"
                        },
                        new
                        {
                            Id = 9,
                            HallId = 3,
                            ImageUrl = "Hall (9).jpeg"
                        },
                        new
                        {
                            Id = 10,
                            HallId = 4,
                            ImageUrl = "Hall (10).jpeg"
                        },
                        new
                        {
                            Id = 11,
                            HallId = 4,
                            ImageUrl = "Hall (11).jpeg"
                        },
                        new
                        {
                            Id = 12,
                            HallId = 4,
                            ImageUrl = "Hall (12).jpeg"
                        });
                });

            modelBuilder.Entity("MVC_Projec2.Models.MakeUpImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MakeUp_ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MakeUp_ServiceId");

                    b.ToTable("MakeUpImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "makeUp1.jpg",
                            MakeUp_ServiceId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "makeUp2.jpg",
                            MakeUp_ServiceId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "makeUp3.jpg",
                            MakeUp_ServiceId = 1
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "makeUp4.jpg",
                            MakeUp_ServiceId = 2
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "makeUp5.jpg",
                            MakeUp_ServiceId = 2
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "makeUp6.jpg",
                            MakeUp_ServiceId = 2
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "makeUp7.jpg",
                            MakeUp_ServiceId = 3
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "makeUp8.jpg",
                            MakeUp_ServiceId = 3
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "MakeUp (1).jpeg",
                            MakeUp_ServiceId = 3
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "MakeUp (2).jpeg",
                            MakeUp_ServiceId = 4
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "MakeUp (3).jpeg",
                            MakeUp_ServiceId = 4
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "MakeUp (4).jpeg",
                            MakeUp_ServiceId = 4
                        });
                });

            modelBuilder.Entity("MVC_Projec2.Models.MakeUp_Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MakeUpServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Elegant and long-lasting bridal look tailored for your special day.",
                            ImageUrl = "makeUp1.jpg",
                            Name = "Bridal Makeup",
                            Price = 1500
                        },
                        new
                        {
                            Id = 2,
                            Description = "Bold, vibrant look perfect for parties and night-outs.",
                            ImageUrl = "makeUp2.jpg",
                            Name = "Party Glam",
                            Price = 800
                        },
                        new
                        {
                            Id = 3,
                            Description = "Soft, minimal makeup enhancing your natural beauty.",
                            ImageUrl = "makeUp3.jpg",
                            Name = "Natural Look",
                            Price = 500
                        },
                        new
                        {
                            Id = 4,
                            Description = "Sophisticated makeup style ideal for evening events.",
                            ImageUrl = "makeUp4.jpg",
                            Name = "Evening Elegance",
                            Price = 1000
                        },
                        new
                        {
                            Id = 5,
                            Description = "Shiny, high-glam look with glowing highlights and contouring.",
                            ImageUrl = "makeUp5.jpg",
                            Name = "Glamour Shine",
                            Price = 1200
                        },
                        new
                        {
                            Id = 6,
                            Description = "Colorful and creative look, perfect for festivals and themed events.",
                            ImageUrl = "makeUp6.jpg",
                            Name = "Festival Glam",
                            Price = 700
                        },
                        new
                        {
                            Id = 7,
                            Description = "Radiant bridal makeup focused on glowing skin and soft tones.",
                            ImageUrl = "makeUp7.jpg",
                            Name = "Bridal Glow",
                            Price = 1600
                        },
                        new
                        {
                            Id = 8,
                            Description = "Tailored makeup style for birthdays, graduations, and formal events.",
                            ImageUrl = "makeUp8.jpg",
                            Name = "Special Occasion",
                            Price = 1300
                        },
                        new
                        {
                            Id = 9,
                            Description = "Inspired by red carpet celebrities with dramatic, flawless finish.",
                            ImageUrl = "MakeUp (9).jpeg",
                            Name = "Celebrity Look",
                            Price = 2000
                        },
                        new
                        {
                            Id = 10,
                            Description = "Effortless and neat makeup for a clean and graceful appearance.",
                            ImageUrl = "MakeUp (10).jpeg",
                            Name = "Simple Elegance",
                            Price = 600
                        });
                });

            modelBuilder.Entity("MVC_Projec2.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Professional photo session for any occasion.",
                            Duration = 2,
                            ImageUrl = "session1.jpg",
                            Location = "Studio A",
                            Name = "Photography Session",
                            Price = 1000.0,
                            Type = "Photography"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Capture every moment with cinematic quality.",
                            Duration = 3,
                            ImageUrl = "session2.jpg",
                            Location = "Outdoor Locations",
                            Name = "Cinematic Videography",
                            Price = 1500.0,
                            Type = "Videography"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Celebrate your engagement with a memorable shoot.",
                            Duration = 4,
                            ImageUrl = "session3.jpg",
                            Location = "Romantic Spots",
                            Name = "Engagement Shoot",
                            Price = 2000.0,
                            Type = "Engagement Shoot"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Romantic photo session before your big day.",
                            Duration = 5,
                            ImageUrl = "session4.jpg",
                            Location = "Garden Venue",
                            Name = "Pre-Wedding Shoot",
                            Price = 2500.0,
                            Type = "Pre-Wedding Shoot"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Full-day photography service for weddings.",
                            Duration = 6,
                            ImageUrl = "session5.jpg",
                            Location = "Wedding Venue",
                            Name = "Wedding Photography",
                            Price = 4000.0,
                            Type = "Wedding Photography"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Capture the love and connection between you two.",
                            Duration = 2,
                            ImageUrl = "session6.jpg",
                            Location = "Scenic Outdoor Locations",
                            Name = "Couple's Love Shoot",
                            Price = 1200.0,
                            Type = "Couple Shoot"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Elegant portraits for the bride in her gown.",
                            Duration = 3,
                            ImageUrl = "session7.jpg",
                            Location = "Studio",
                            Name = "Bridal Portrait Session",
                            Price = 1800.0,
                            Type = "Bridal Portraits"
                        },
                        new
                        {
                            Id = 8,
                            Description = "High-end fashion shoot for models or brands.",
                            Duration = 4,
                            ImageUrl = "session8.jpg",
                            Location = "Fashion Studio",
                            Name = "High Fashion Shoot",
                            Price = 2200.0,
                            Type = "Fashion Photography"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Photography and videography coverage for events.",
                            Duration = 5,
                            ImageUrl = "session9.jpg",
                            Location = "Event Venue",
                            Name = "Event Photography & Videography",
                            Price = 3000.0,
                            Type = "Event Coverage"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Heartwarming family photography session.",
                            Duration = 3,
                            ImageUrl = "session3.jpg",
                            Location = "Home or Outdoor",
                            Name = "Family Photography",
                            Price = 1400.0,
                            Type = "Family Shoot"
                        });
                });

            modelBuilder.Entity("MVC_Projec2.Models.SessionImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "session1.jpg",
                            SessionId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "session2.jpg",
                            SessionId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "session3.jpg",
                            SessionId = 1
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "session4.jpg",
                            SessionId = 2
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "session5.jpg",
                            SessionId = 2
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "session6.jpg",
                            SessionId = 2
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "session7.jpg",
                            SessionId = 3
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "session8.jpg",
                            SessionId = 3
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "session9.jpg",
                            SessionId = 3
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "session1.jpg",
                            SessionId = 4
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "session8.jpg",
                            SessionId = 4
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "session4.jpg",
                            SessionId = 4
                        },
                        new
                        {
                            Id = 13,
                            ImageUrl = "session2.jpg",
                            SessionId = 5
                        },
                        new
                        {
                            Id = 14,
                            ImageUrl = "session7.jpg",
                            SessionId = 5
                        },
                        new
                        {
                            Id = 15,
                            ImageUrl = "session5.jpg",
                            SessionId = 5
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {




                            UserId = "09970960-568f-421a-855d-9c2e22205af2",

                            RoleId = "1"
                        },
                        new
                        {




                            UserId = "8aa98e10-33a4-412a-8cd4-edb609f077d5",

                            RoleId = "2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MVC_Projec2.Models.AtelierImages", b =>
                {
                    b.HasOne("MVC_Projec2.Models.Atelier", "Atelier")
                        .WithMany("Images")
                        .HasForeignKey("AtelierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atelier");
                });

            modelBuilder.Entity("MVC_Projec2.Models.Booking", b =>
                {
                    b.HasOne("MVC_Projec2.Models.Atelier", "Atelier")
                        .WithMany()
                        .HasForeignKey("Atelier_Id");

                    b.HasOne("MVC_Projec2.Models.Decor", "Decor")
                        .WithMany()
                        .HasForeignKey("Decor_Id");

                    b.HasOne("MVC_Projec2.Models.Hall", "Hall")
                        .WithMany()
                        .HasForeignKey("Hall_Id");

                    b.HasOne("MVC_Projec2.Models.MakeUp_Service", "MakeUp")
                        .WithMany()
                        .HasForeignKey("MakeupId");

                    b.HasOne("MVC_Projec2.Models.Session", "Session")
                        .WithMany()
                        .HasForeignKey("Session_Id");

                    b.HasOne("MVC_Projec2.Models.ApplicationUser", "user")
                        .WithMany("Bookings")
                        .HasForeignKey("user_id");

                    b.Navigation("Atelier");

                    b.Navigation("Decor");

                    b.Navigation("Hall");

                    b.Navigation("MakeUp");

                    b.Navigation("Session");

                    b.Navigation("user");
                });

            modelBuilder.Entity("MVC_Projec2.Models.Comment", b =>
                {
                    b.HasOne("MVC_Projec2.Models.ApplicationUser", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MVC_Projec2.Models.DecoreImage", b =>
                {
                    b.HasOne("MVC_Projec2.Models.Decor", "Decor")
                        .WithMany("Images")
                        .HasForeignKey("DecorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Decor");
                });

            modelBuilder.Entity("MVC_Projec2.Models.HallImage", b =>
                {
                    b.HasOne("MVC_Projec2.Models.Hall", "Hall")
                        .WithMany("Images")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("MVC_Projec2.Models.MakeUpImages", b =>
                {
                    b.HasOne("MVC_Projec2.Models.MakeUp_Service", "makeUp")
                        .WithMany("Images")
                        .HasForeignKey("MakeUp_ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("makeUp");
                });

            modelBuilder.Entity("MVC_Projec2.Models.SessionImages", b =>
                {
                    b.HasOne("MVC_Projec2.Models.Session", "Session")
                        .WithMany("Images")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("MVC_Projec2.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MVC_Projec2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MVC_Projec2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("MVC_Projec2.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVC_Projec2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MVC_Projec2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MVC_Projec2.Models.ApplicationUser", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("MVC_Projec2.Models.Atelier", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("MVC_Projec2.Models.Decor", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("MVC_Projec2.Models.Hall", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("MVC_Projec2.Models.MakeUp_Service", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("MVC_Projec2.Models.Session", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
